import type { FoundItem } from '@/lib/definitions';

export const dummyFoundItems: FoundItem[] = [
  {
    id: '1',
    name: 'Blue Backpack',
    description: 'A blue Jansport backpack, feels like it has a laptop inside. Found near the main library entrance.',
    location: 'Library',
    dateFound: '2024-07-20',
    imageUrl: 'https://picsum.photos/seed/backpack1/600/400',
    imageHint: 'blue backpack',
    contact: 'j.doe@university.edu',
  },
  {
    id: '2',
    name: 'iPhone 13',
    description: 'Black iPhone 13 with a small crack on the top left of the screen. The case is clear with some stickers on it.',
    location: 'Student Union Cafeteria',
    dateFound: '2024-07-19',
    imageUrl: 'https://picsum.photos/seed/phone1/600/400',
    imageHint: 'smartphone screen',
    contact: 'lostandfound@university.edu',
  },
  {
    id: '3',
    name: 'Car Keys',
    description: 'A set of keys with a red university lanyard. Includes a Honda car key and two smaller keys.',
    location: 'Parking Lot C',
    dateFound: '2024-07-21',
    imageUrl: 'https://picsum.photos/seed/keys1/600/400',
    imageHint: 'set keys',
    contact: 'security@university.edu',
  },
  {
    id: '4',
    name: 'Leather Wallet',
    description: 'A brown, worn leather wallet. No ID inside but contains some cash and credit cards. Found on a bench.',
    location: 'Central Quad',
    dateFound: '2024-07-18',
    imageUrl: 'https://picsum.photos/seed/wallet1/600/400',
    imageHint: 'leather wallet',
    contact: 'lostandfound@university.edu',
  },
  {
    id: '5',
    name: 'Water Bottle',
    description: 'A large stainless steel Hydro Flask-style water bottle covered in various national park stickers.',
    location: 'Gymnasium',
    dateFound: '2024-07-21',
    imageUrl: 'https://picsum.photos/seed/bottle1/600/400',
    imageHint: 'water bottle',
    contact: 'gymdesk@university.edu',
  },
  {
    id: '6',
    name: 'Silver Laptop',
    description: 'A silver MacBook Air left in a black zip-up case. A charger was also in the case.',
    location: 'Computer Science Building, Room 101',
    dateFound: '2024-07-17',
    imageUrl: 'https://picsum.photos/seed/laptop1/600/400',
    imageHint: 'silver laptop',
    contact: 'csdept@university.edu',
  },
  {
    id: '7',
    name: 'Notebook',
    description: 'A standard black Moleskine notebook. The first page has the name "Alex" written on it. Seems to contain class notes.',
    location: 'Lecture Hall B',
    dateFound: '2024-07-20',
    imageUrl: 'https://picsum.photos/seed/notebook1/600/400',
    imageHint: 'black notebook',
    contact: 'lostandfound@university.edu',
  },
];
